/** Type definitions for tasks */

import { tasks } from '../../schema';

// ============================================================================
// Embedded JSON Types (explicit - used by schema via .$type<T>())
// ============================================================================

/**
 * Step: Embedded in Task (not a separate table)
 * @see docs/architecture/primitives.md
 */
export type Step = {
  id: string; // ULID
  ref: string; // Human-readable identifier (unique per task)
  ordinal: number; // Execution order (0-indexed)

  action_id: string; // FK → actions
  action_version: number;

  input_mapping: object | null; // Map task context → action input
  output_mapping: object | null; // Map action output → task context

  on_failure: 'abort' | 'retry' | 'continue'; // Default: abort

  condition: {
    if: string; // Expression evaluated against task context
    then: 'continue' | 'skip' | 'succeed' | 'fail';
    else: 'continue' | 'skip' | 'succeed' | 'fail';
  } | null;
};

export type RetryConfig = {
  max_attempts: number;
  backoff: 'none' | 'linear' | 'exponential';
  initial_delay_ms: number;
  max_delay_ms: number | null;
};

/** Step input - id is generated by the RPC layer */
export type StepInput = Omit<Step, 'id'>;

// ============================================================================
// Entity Types (inferred from schema)
// ============================================================================

/** Task entity - inferred from database schema */
export type Task = typeof tasks.$inferSelect;

// ============================================================================
// API DTOs (explicit - have fields not in DB)
// ============================================================================

export type TaskInput = {
  version?: number;
  name: string;
  description?: string;
  project_id?: string;
  library_id?: string;
  tags?: string[];
  input_schema: object;
  output_schema: object;
  steps: StepInput[];
  retry?: RetryConfig;
  timeout_ms?: number;
  autoversion?: boolean;
};
