/** Type definitions for tasks */

// ============================================================================
// Embedded JSON Types
// ============================================================================

/**
 * Step: Embedded in Task (not a separate table)
 * @see docs/architecture/primitives.md
 */
export type Step = {
  id: string; // ULID
  ref: string; // Human-readable identifier (unique per task)
  ordinal: number; // Execution order (0-indexed)

  actionId: string; // FK → actions
  actionVersion: number;

  inputMapping: Record<string, unknown> | null; // Map task context → action input
  outputMapping: Record<string, unknown> | null; // Map action output → task context

  onFailure: 'abort' | 'retry' | 'continue'; // Default: abort

  condition: {
    if: string; // Expression evaluated against task context
    then: 'continue' | 'skip' | 'succeed' | 'fail';
    else: 'continue' | 'skip' | 'succeed' | 'fail';
  } | null;
};

export type RetryConfig = {
  maxAttempts: number;
  backoff: 'none' | 'linear' | 'exponential';
  initialDelayMs: number;
  maxDelayMs: number | null;
};

/** Step input - id is generated by the RPC layer */
export type StepInput = Omit<Step, 'id'>;

// ============================================================================
// Entity Types
// ============================================================================

/**
 * Task entity - the API-facing shape.
 * Internally stored in the unified `definitions` table.
 */
export type Task = {
  id: string;
  version: number;
  name: string;
  description: string;
  reference: string;
  projectId: string | null;
  libraryId: string | null;
  tags: string[] | null;
  inputSchema: object;
  outputSchema: object;
  steps: Step[];
  retry: RetryConfig | null;
  timeoutMs: number | null;
  contentHash: string;
  createdAt: string;
  updatedAt: string;
};

// ============================================================================
// API DTOs
// ============================================================================

/**
 * API input for creating a task.
 */
export type TaskInput = {
  name: string;
  description?: string;
  reference?: string;
  projectId?: string | null;
  libraryId?: string | null;
  tags?: string[] | null;
  inputSchema: Record<string, unknown>;
  outputSchema: Record<string, unknown>;
  steps: StepInput[];
  retry?: RetryConfig | null;
  timeoutMs?: number | null;
  autoversion?: boolean;
};
