/** Type definitions for tasks */

import { tasks } from '../../schema';

// ============================================================================
// Embedded JSON Types (explicit - used by schema via .$type<T>())
// ============================================================================

/**
 * Step: Embedded in Task (not a separate table)
 * @see docs/architecture/primitives.md
 */
export type Step = {
  id: string; // ULID
  ref: string; // Human-readable identifier (unique per task)
  ordinal: number; // Execution order (0-indexed)

  actionId: string; // FK → actions
  actionVersion: number;

  inputMapping: object | null; // Map task context → action input
  outputMapping: object | null; // Map action output → task context

  onFailure: 'abort' | 'retry' | 'continue'; // Default: abort

  condition: {
    if: string; // Expression evaluated against task context
    then: 'continue' | 'skip' | 'succeed' | 'fail';
    else: 'continue' | 'skip' | 'succeed' | 'fail';
  } | null;
};

export type RetryConfig = {
  maxAttempts: number;
  backoff: 'none' | 'linear' | 'exponential';
  initialDelayMs: number;
  maxDelayMs: number | null;
};

/** Step input - id is generated by the RPC layer */
export type StepInput = Omit<Step, 'id'>;

// ============================================================================
// Entity Types (inferred from schema)
// ============================================================================

/** Task entity - inferred from database schema */
export type Task = typeof tasks.$inferSelect;

// ============================================================================
// API DTOs (explicit - have fields not in DB)
// ============================================================================

export type TaskInput = {
  version?: number;
  name: string;
  description?: string;
  projectId?: string;
  libraryId?: string;
  tags?: string[];
  inputSchema: object;
  outputSchema: object;
  steps: StepInput[];
  retry?: RetryConfig;
  timeoutMs?: number;
  autoversion?: boolean;
};
