#!/usr/bin/env tsx
/**
 * Generate TypeScript types and client from OpenAPI spec.
 *
 * Phase 1: Generate types with custom transform hooks
 * Phase 2: Parse paths and generate client code
 * Phase 3: Write both files to src/generated/
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import openapiTS from 'openapi-typescript';
import ts from 'typescript';
import { formatClientCode, generateRootClient } from './generate-client.js';
import { buildRouteTree, type HttpMethod, type PathDefinition } from './parse-paths.js';

const API_URL = process.env.API_URL || 'https://wonder-http.ron-keiser.workers.dev';

/**
 * Convert OpenAPI paths object to PathDefinition array
 */
export function convertOpenApiPaths(paths: Record<string, Record<string, any>>): PathDefinition[] {
  const result: PathDefinition[] = [];

  for (const [path, methods] of Object.entries(paths)) {
    for (const [method, operation] of Object.entries(methods)) {
      // Only include valid HTTP methods
      if (['get', 'post', 'put', 'patch', 'delete'].includes(method)) {
        result.push({
          path,
          method: method as HttpMethod,
          operationId: operation?.operationId,
          responses: operation?.responses,
        });
      }
    }
  }

  return result;
}

async function generate() {
  console.log(`Fetching OpenAPI spec from ${API_URL}/doc...`);

  // Fetch OpenAPI spec as JSON for path parsing
  const response = await fetch(`${API_URL}/doc`);
  const spec = (await response.json()) as { paths: Record<string, Record<string, any>> };

  // Generate TypeScript types
  const ast = await openapiTS(`${API_URL}/doc`, {
    transform(schemaObject, options) {
      const path = options.path || '';

      // Intercept schema fields and replace with SchemaType reference
      if (
        path.endsWith('input_schema') ||
        path.endsWith('output_schema') ||
        path.endsWith('context_schema')
      ) {
        return ts.factory.createTypeReferenceNode('SchemaType');
      }

      // Use default transformation for everything else
      return undefined;
    },
  });

  // Add import statement for SchemaType
  const importStatement = ts.factory.createImportDeclaration(
    undefined, // modifiers
    ts.factory.createImportClause(
      true, // isTypeOnly
      undefined, // name
      ts.factory.createNamedImports([
        ts.factory.createImportSpecifier(
          false, // isTypeOnly
          undefined, // propertyName
          ts.factory.createIdentifier('SchemaType'),
        ),
      ]),
    ),
    ts.factory.createStringLiteral('@wonder/context'),
    undefined, // attributes
  );

  // Combine import + generated AST
  const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed });
  const sourceFile = ts.createSourceFile(
    'schema.d.ts',
    '',
    ts.ScriptTarget.Latest,
    false,
    ts.ScriptKind.TS,
  );

  // Print import statement
  const importCode = printer.printNode(ts.EmitHint.Unspecified, importStatement, sourceFile);

  // Print generated types
  const typesCode = ast
    .map((node) => printer.printNode(ts.EmitHint.Unspecified, node, sourceFile))
    .join('\n\n');

  const header = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

`;

  const schemaOutput = header + importCode + '\n\n' + typesCode;

  // Task 3.2: Parse routes into tree structure
  console.log('Parsing API routes...');
  const pathDefs = convertOpenApiPaths(spec.paths);
  const routeTree = buildRouteTree(pathDefs);

  // Task 3.3: Generate client structure
  console.log('Generating client code...');
  const clientStructure = generateRootClient(routeTree);

  // Task 3.4: Format client code
  const clientOutput = formatClientCode(clientStructure);

  // Task 3.5: Write files
  const schemaPath = 'src/generated/schema.d.ts';
  const clientPath = 'src/generated/client.ts';

  // Ensure directory exists
  await mkdir(dirname(schemaPath), { recursive: true });

  // Write schema types
  await writeFile(schemaPath, schemaOutput, 'utf-8');
  console.log(`✓ Generated types written to ${schemaPath}`);

  // Write client code
  await writeFile(clientPath, clientOutput, 'utf-8');
  console.log(`✓ Generated client written to ${clientPath}`);
}

generate().catch((err) => {
  console.error('Generation failed:', err);
  process.exit(1);
});
